### ISSUE TITLE
Application 404 on initial running

### ISSUE THREAD

**Issue by kishea-dev** [amizayi/admin-panel#76]
Panel not loading.
404 on initial running of all commands in the readme.

**Comment by amizayi** [comment]
Hello, my friend 🙌.

I've created this modular project to jumpstart the development of all admin panels that are managed through APIs. The initial objective was to include all the necessary modules within the project to facilitate a quick start🚀.

If I find the time, I will also add LiveWire and Filament to this repository in the near future. If you encounter any problems or have specific requests, please don't hesitate to open a new issue, and I'll do my best to assist you further❤️🍷.

Thank you for taking the time to contribute🙏.
